Adding fraxBP and alUSD/SUSD/USDT metapools
saddle-finance/saddle-contract pull request #636
Opened 2022-06-23 21:04 UTC by mjdatadog

WIP Adding frax/USD base pools and metapools

2022-06-24 14:14 UTC, hannespfeiffer requested changes
Just potentially removing alUSD registry adds on Arb and Opt

2022-06-24 14:14 UTC, hannespfeiffer commented on deploy/arbitrum/999_register_new_pools.ts
> +    },
Not adding alUSD atm, correct?

2022-06-24 14:14 UTC, hannespfeiffer commented on deploy/optimism/999_register_new_pools.ts
> +    },
Same here

2022-06-27 18:12 UTC, penandlim approved these changes

2022-06-27 18:12 UTC, merged