Kava mainnet 2pool deploy
saddle-finance/saddle-contract pull request #648
Opened 2022-07-05 22:24 UTC by mjdatadog

# Deploy Pull Request Template

## Description

Deploying initialize contracts for first kava mainnet deploy.

Fixes # (issue)

## Deployment checklist

List any new deployments that is expected to be saved after running the deploy task. After running the scripts, check off each item if they are successfully deployed.

- [ ] Kava2Pool
- [ ] Kava2PoolLPToken

## Deployment verification

Please provide explorer links to the deployed contracts and verify them using either standard solcInputs json or manually flattened contracts using `npx hardhat flatten`. After verifying them, check off each item.

- [ ] Link to Kava2Pool on etherscan
- [ ] Link to Kava2PoolLPToken on etherscan

## Checklist:

- [ ] Any imported tokens's addresses are verified against official docs
- [ ] If any existing contracts are changed, ensure the saved deployments are removed before running the deploy scripts
- [ ] If deploying a new pool on a testnet, ensure there is liquidity by providing the test tokens to a DEX.
- [ ] If possible, the deploy scripts are tested against forked mainnet or local hardhat node.
- [ ] Newly deployed contracts match the expected list of new deployments
- [ ] All newly deployed contracts are verified on explorers

2022-07-18 19:25 UTC, hannespfeiffer requested changes

2022-07-18 19:25 UTC, hannespfeiffer commented on deploy/kava_mainnet/110_check_Kava3PoolTokens.ts
> +  FRAX: ["Tether", "USDT", "6"],
Token args

2022-07-18 21:53 UTC, hannespfeiffer approved these changes

2022-07-21 20:23 UTC, penandlim approved these changes

2022-07-29 19:30 UTC, merged